### PR TITLE
New template: example (very simple working game). 

### PR DESCRIPTION
**Pull request by cha55son**
There are a few new features here:
- When creating a project you can now specify what kind of game to create. (very limited at the moment) Each game type is functional and listed below:
  - **minimal**: The generator will copy the files required to get the server running.
  - **example**: A simple game where you may control a character, also the server moves a tree around randomly.
- When creating a project you can specify **--development** which will instead of copying files will sym-link them so editing within your project will edit the versioned files within impact-crater-core. _Makes development easier for me, if there is a better way to do this, please let me know._
- Updated the README to include the new features as well as streamline the installation process.

### CODE REVIEW

**Comment by cha55son** [comment]
If you don't mind, can you test the README and check all the steps as well as try the different game types. Just want to make sure nothing slips through the cracks here.

**Comment by dylan** [comment]
Sure can.

**Comment by cha55son** [comment]
I would like to get this merged in tonight. I'll check it out again and run tests while following the readme. If all goes well i'll accept the pull-request.

Sorry for the short notice on this pull request. I found some time to do some work on it and wanted to clean up the installation process as well as build upon your template idea. (Which works well) I want to get this release into the wild b/c i've gotten some emails about the installation process being difficult as well as not having functional templates from the get-go.

**Comment by dylan** [comment]
Sounds good. I'm busy today and probably couldn't test till later tonight.

**Pull request merged**
