### PR TITLE
Feature/modularization

### PR DESCRIPTION
**Pull request by dylan**
I wanted to be able to run a test project on the side/develop modules without relying on the .gitgnore file or checking out a repo every time I wanted to start a project so I whipped together this CLI tool for performing various tasks. One big initial gain is that you can update this framework in your dev repo for it, and run the tool on your test folder and it will overwrite the files that've changed. Ping me via email or gchat if you want a walkthrough... :smile:

### CODE REVIEW

**Comment by cha55son** [comment]
This is a good idea, I haven't gotten around to fixing this glaring problem. I'm testing at the moment.

The first problem I ran into is after I link I cannot install globally, although i'm not sure you need to. Below are the commands I ran to get it to link properly.

```
git clone <impact-crater>
cd impact-crater
npm link
cd ../
mkdir my-mp-game
cd my-mp-game
npm link impact-crater
```

I'm on mac OSX 10.9
NPM 1.3.11
Node v0.10.21

**EDIT:** Sorry, didn't see the bottom of the readme. Makes sense now.

**Comment by dylan** [comment]
You need to npm link dir/to/local/impact-crater from inside the new project to make it use your local version of the module. Make sense?

**Comment by dylan** [comment]
The process should be

```
git clone
cd into impact-crater
npm link
cd ..
impact-crater generate my-new-game
cd my-new-game
npm link path/to/cloned/impact-crater
```

**Comment by cha55son** [comment]
When running 

```
impact-crater generate my-new-game
```

I don't have the coffee bin script, that will need to be added to the dependencies.

```
env: coffee: No such file or directory
```

**Comment by dylan** [comment]
Should have been installed with npm link in the impact-crater

**Comment by cha55son** [comment]
I had to run this to get the bin script to work

```
npm install -g coffee-script
```

**Comment by dylan** [comment]
Ok, I'll look into fixing that. Thanks for checking this out.

**Comment by cha55son** [comment]
Steps to recreate:
- Clone impact-crater and run `npm link`
- Create the game `impact-crater generate my-mp-game`
- cd into my-mp-game and run `npm link impact-crater`
- Copy game code into `my-mp-game/impact/`
- Run `impact-crater start`

The error I get is 

`Error: Cannot find module 'express'`

Which is strange since I can clearly see that `impact-crater` has express within it's `node_modules`.

**Comment by dylan** [comment]
Odd, looking into it now.

**Comment by cha55son** [comment]
Yea I had to install `ejs, express, and socket.io` in my `my-mp-game/node_modules/` dir for the server to start up.

**Comment by dylan** [comment]
I thought that it would inherit all the deps of impact-crater, looking into why it doesn’t :(

**Comment by cha55son** [comment]
Alright testing again,

Here's what I encountered:
- I still have to run `npm install coffee-script -g` before I can run `impact-crater generate`. Not a big deal just add it as a step in the README.
- If I run impact-crater by itself it shows me the instructions specifically this one: `impact-crater generate basic my-mp-game` If I run that command it creates a folder named `basic` not `my-mp-game`.

**Comment by cha55son** [comment]
It seems the port option doesn't work for the bin script. Could you comment references to that out until that is functioning. Otherwise i'm ready to merge.

**Pull request merged**
